---
- hosts: ios            # 対象のグループ名（インベントリファイル内の定義）
  gather_facts: false   # システム情報収集機能の無効化（時間短縮のため）

  # ここからタスクの定義
  tasks:
    # タスク1: 参照NTPサーバーの設定
    - name: config ntp
      cisco.ios.ios_config:
        lines:    # 投入したい設定コマンドを指定
          - ntp server 10.0.0.11
          - ntp server 10.0.0.12
